---
services:

  # streamlit 예제
  streamit:
    image: illey/streamlit
    build:
      context: .
      dockerfile: ./docker/Dockerfile.streamlit

    ports:
      - "8180:8080"
    volumes:
      - ./streamlit/app:/app

  # fastapi 예제
  fastapi:
    image: illey/fastapi
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fastapi

    ports:
      - "8280:8080"
    volumes:
      - ./fastapi/app:/app

  # html(nginx) 예제
  web:
    image: illey/web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web

    ports:
      - "8080:80"
    volumes:
      - ./web/html:/usr/share/nginx/html

  database:
    image: mysql:8.4.4
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci --log_bin_trust_function_creators=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      start_period: 30s
      interval: 15s
      timeout: 30s
      retries: 5