---

services:
  streamit:
    image: bppp/streamlit
    build:
      context: .
      dockerfile: ./docker/Dockerfile.streamlit

    ports:
      - "8180:8080"
    volumes:
      - ./streamlit/app:/app

  fastapi:
    image: bppp/fastapi
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fastapi

    ports:
      - "8280:8080"
    volumes:
      - ./fastapi/app:/app

  web:
    image: bppp/web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web

    ports:
      - "8080:80"
    volumes:
      - ./web/html:/usr/share/nginx/html